# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-03-21 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_news',
            name='image_link',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AddField(
            model_name='audio_news',
            name='original_link',
            field=models.CharField(default='-', max_length=400),
        ),
    ]
